### PR TITLE
Allow locking axes on Follow modifier

### PR DESCRIPTION
**Pull request by aXu-AP**
This functionality is used for sidescroller (2.5D) and top-down views.

### CODE REVIEW

**Review by Bryce-Dixon — APPROVED** [review]
Definitely a good addition. I kinda wish GDScript had a feature like bitfields in C++ to make the masking look cleaner, but maybe it can get revisited in the future.

**Comment by aXu-AP** [comment]
There's possibility to group variables in inspector, but it doesn't look much better.
Inspector plugin could be a solution to make it cleaner but is it overkill?

**Comment by Bryce-Dixon** [comment]
Oh, I'm specifically referring to using the variables in code.

```cpp
//C++
#include <iostream>

struct AxisFlags
{
  // Each of these will take up 1 bit abd be packed into a single byte
  bool x : 1{ false };
  bool y : 1{ false };
  bool z : 1{ false };
};

void main()
{
  AxisFlags enabledAxes{};
  std::cout << sizeof(enabledAxes) << '\n'; // 1
  enabledAxes.x = true;
  if (enabledAxes.y)
  {
    //Much easier to read this way
  }
}
```

**Comment by aXu-AP** [comment]
Ah sorry I must have been half asleep. That definitely would be a nice functionality! Currently enums are closest we have (but for use case as simple and unchanging as XYZ I felt hardcoding the bits were better fit).

**Pull request merged**
